---
lgtm_manifest_file: files/dev-manifest.xml
lgtm_certificate_file: files/dev.crt
lgtm_key_file: files/dev.key
lgtm_external_url: https://localhost:8443
lgtm_ghe_hostname: git.company.invalid
lgtm_ghe_url: https://{{ lgtm_ghe_hostname }}


lgtm_controller_ansible_name: "{{ groups['controller'][0] }}"
lgtm_controller_hostname: "{{ hostvars[lgtm_controller_ansible_name]['ansible_default_ipv4']['address'] }}"


lgtm_manifest_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65663964323164626336363335386434666563373463393035356266366463303136306231373635
          3038376431613538643161393139646331346339393831370a626630666634623134303761373139
          38323833663534626339353737396630666662643230336664643439626135343435326137393339
          3563376430326133610a363465653334316232393631383634633133393365643263646539373636
          62376337393338613038353634656434633564373531356530626261343032613836
lgtm_ghe_checkout_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38393230313131626538393663626639353535633063333664346564656239353135643366653539
          3938666566393366313430393833353263373731643762360a393634343539333437326230383732
          39633934386262393331353436643739626639643564306431326631373462623132333063383366
          3863613030666266660a383432666565623633383664623232323336663235393965613633383533
          3664
lgtm_ghe_checkout_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35303462653630653164383061336666623032366165636533373233656662613439613339383166
          3562373830366338383265383533323564663938383063350a333933336663643465626366326135
          65616437663539623833346639363933343766663336616161636333326263663866303162313563
          3261393563653362640a666264396565626437383263376230663562313865623436363966323261
          6361
lgtm_ghe_client_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38623631316537343563303839393032326236346232656465383534323933666265616431633338
          6264386464656161363161376533323137353562633231380a643534393130626633663364303862
          30383436643164613133366331353634616161633334646639636635323463336265383065356338
          3265373633316135660a353230376332623137396263396339363234646664343632366239636232
          37333936343466626462396361643938613732383764356331613936343963363530
lgtm_ghe_client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30343764656631656639626634663862333135373733633664303533313339323235353434643530
          3434303238663166663465623465303136303466343531360a333164616435363463653536316136
          34396166633634633230303137376435336435333865313663306633373336633133333233333762
          3266353332383432620a326466323331363164373635353532616562656630313837353033653433
          38336131306431386261383962343632306264336166326233333165333166346332383466623937
          3764343030366132306535356365623030383939656463316462
